### ISSUE TITLE
Rings and Weapons not working together

### ISSUE THREAD

**Issue by pinwazkev** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#8] opened 2018-07-10 11:54 UTC
When im wearing a ring and holding air its active, but when I hold a sword while wearing a ring it removes rings buffs.

**Comment by TheXFactor117** [comment] 2018-07-10 13:14
I'll look into it - I think I know what the issue is.

**Comment by TheXFactor117** [comment] 2018-07-12 18:51
Should be fixed in 0.6.1.1 - re-open this if the issue still occurs.

**Closed as completed by TheXFactor117** 2018-07-12 18:51 UTC
Labels: Bug
