### ISSUE TITLE
Nameplates link level and rank

### ISSUE THREAD

**Issue by PCSpinner** [TheXFactor117/Loot-Slash-Conquer-Pre1.14#42] opened 2018-09-14 06:00 UTC
Forge 14.23.4.2759
Loot+Slash+Conquer 0.6.1.2
Baubles 1.5.2

All level 1 monsters are marked as "normal". All level 2 are "Hardened". All L3 are "Superior"; L4 "Epic"; and L5 "Legendary". Anything level 6 or higher is marked as "Default".

Monsters of the same level occasionally have increased health, so this seems to be a visual bug.

**Comment by TheXFactor117** [comment] 2019-03-11 00:24
I'll look into it, I believe I know what the issue is.

**Comment by TheXFactor117** [comment] 2019-05-13 19:15
Should be fixed in 0.6.2.0.

**Closed as completed by TheXFactor117** 2019-05-13 19:15 UTC
Labels: Bug
